### ISSUE TITLE
encode Chinese error

### ISSUE THREAD

**Issue by alecm20** [trentmillar/md5-o-matic#1]
hello, the result that  Chinese character encoded by the function is wrong,
such:
var a = md5omatic('你好')
// the result: "c50de6c887d23676fa37a4b174300120"

encoded by other md5 lib, get the right result,
// 7eca689f0d3389d9dea66ae112e5cfd7

**Comment by trentmillar** [comment]
Feel free to - fork, clone, code, push, PR, fixed.
